name: CLI Ops
on:
  push:
    paths:
      - 'cli/**'
      - 'scripts/**'
      - '.github/workflows/_release-cli.yml'
  workflow_dispatch:

jobs:
  release:
    uses: ./.github/workflows/npm-release-ops.yml
    with:
      registry_url: https://registry.npmjs.org/
      build_command: "" # CLI doesn't need build
      test_command: "npm test"
      working_directory: "cli"
    secrets:
      npm_token: ${{ secrets.npm_token }}
