name: Repository Ops

on:
  push:
    paths:
      - 'cli/**'
      - 'scripts/**'
      - '.github/workflows/internal/**'
  workflow_dispatch:

jobs:
  test:
    name: Test CLI
    uses: ./.github/workflows/internal/test-cli.yml

  release:
    name: Release CLI
    if: github.ref == 'refs/heads/master'
    uses: ./.github/workflows/internal/release-cli.yml
    secrets: inherit
